import { VideoItem } from './types';

export const VIDEOS: VideoItem[] = [
  // --- 12 VERTICAL ITEMS (9:16) ---
  {
    id: 'v1',
    title: 'Warm Podcast Conversation',
    category: 'vertical',
    tag: 'Podcast',
    subtitle: 'Dialogue Cut',
    caption: 'Dialogue Cut',
    thumbnail: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-recording-a-podcast-in-studio-40552-large.mp4',
    description: 'Cinematic high-fidelity podcast edit. Focused on dialogue pacing, multi-cam matching, and custom warm REC.709 color correction.',
    skillsUsed: ['Dialogue Pacing', 'Multi-Cam Match', 'Color Grading'],
    aspectRatio: '9:16'
  },
  {
    id: 'v2',
    title: 'Abstract Gradient Motion',
    category: 'vertical',
    tag: 'Motion Art',
    subtitle: 'Abstract Shapes',
    caption: 'Abstract Gradient',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-gradient-fluid-flowing-colors-44754-large.mp4',
    description: 'Dynamic green gradient visual styled with mathematical symbols and crosshairs. Explores pure visual rhythm and modern minimal layouts.',
    skillsUsed: ['Vector Overlays', 'Visual Rhythm', 'Minimalism'],
    aspectRatio: '9:16'
  },
  {
    id: 'v3',
    title: 'Podcast Interview (Open)',
    category: 'vertical',
    tag: 'Interview',
    subtitle: 'The Open Series',
    caption: 'Open',
    thumbnail: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-breaking-in-the-ocean-1527-large.mp4',
    description: 'High-engagement talking head interview with glasses overlay. Tailored with clean lower thirds and lower panel spacing.',
    skillsUsed: ['Engaging Cuts', 'Subtitling', 'Noise Cancellation'],
    aspectRatio: '9:16'
  },
  {
    id: 'v4',
    title: 'Your Brand Minimalist',
    category: 'vertical',
    tag: 'Minimalism',
    subtitle: 'Your Brand',
    caption: 'Your Brand',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-in-neon-sign-43034-large.mp4',
    description: 'High-fashion aesthetic mood reel demonstrating lighting, minimal white canvas, and subtle center alignment.',
    skillsUsed: ['Speed Ramping', 'Visual Effects', 'Framing'],
    aspectRatio: '9:16'
  },
  {
    id: 'v5',
    title: 'Moody Camera Lens & Clock',
    category: 'vertical',
    tag: 'Cinematic',
    subtitle: 'Camera Work',
    caption: 'Cinematic Shoot',
    thumbnail: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-designer-drawing-on-a-tablet-40437-large.mp4',
    description: 'Moody shot with overlay details like a ticking clock graphic. Custom grading for atmospheric brand engagement.',
    skillsUsed: ['Overlay Elements', 'Atmospheric Grade', 'Sound Design'],
    aspectRatio: '9:16'
  },
  {
    id: 'v6',
    title: 'Inkwell Media White/Black',
    category: 'vertical',
    tag: 'Branding',
    subtitle: 'Inkwell Media',
    caption: 'INKWELL MEDIA',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-of-a-designer-drawing-on-a-tablet-40437-large.mp4',
    description: 'Sleek white-on-black logo Reveal and title presentation. Highlights typographic strength and rhythmic transitions.',
    skillsUsed: ['Logo Reveal', 'Kinetic Typography', 'Sound Effects'],
    aspectRatio: '9:16'
  },
  {
    id: 'v7',
    title: 'Desk Workspace Conversation',
    category: 'vertical',
    tag: 'Lifestyle',
    subtitle: 'Creative Desk',
    caption: 'Creative Flow',
    thumbnail: 'https://images.unsplash.com/photo-1531538606174-0f90ff5dce83?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-holding-a-smartphone-with-a-green-screen-41712-large.mp4',
    description: 'Lifestyle edit showing a designer or developer planning at a desk. Focuses on seamless match-cuts and soft natural color grading.',
    skillsUsed: ['Match Cuts', 'Color Matching', 'Pacing'],
    aspectRatio: '9:16'
  },
  {
    id: 'v8',
    title: 'Bridges & Airport Showcase',
    category: 'vertical',
    tag: 'Infrastructure',
    subtitle: 'Atal Setu & Airport',
    caption: 'Atal Setu Bridge',
    thumbnail: 'https://images.unsplash.com/photo-1541462608141-2f58c8240402?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-walking-alone-in-the-city-at-night-42352-large.mp4',
    description: 'Custom informational reel highlighting the Atal Setu Bridge and Navi Mumbai Airport infrastructure with circular clip frame masks.',
    skillsUsed: ['Informational Layouts', 'Frame Masking', 'Modern Typography'],
    aspectRatio: '9:16'
  },
  {
    id: 'v9',
    title: 'Stanford Brand Campaign',
    category: 'vertical',
    tag: 'Cinematic Portrait',
    subtitle: 'Collegiate Lifestyle',
    caption: 'Stanford',
    thumbnail: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-walking-alone-in-the-city-at-night-42352-large.mp4',
    description: 'A beautiful lifestyle product/brand campaign showcasing collegiate pride, warm natural light grades, and smooth handheld camera tracking movements.',
    skillsUsed: ['Lifestyle Editing', 'Color Grading', 'Camera Tracking', 'Rhythmic Flow'],
    aspectRatio: '9:16'
  },
  {
    id: 'v10',
    title: 'justblitz App UI Screenshot',
    category: 'vertical',
    tag: 'App Tour',
    subtitle: 'justblitz.',
    caption: 'have,',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-holding-a-smartphone-with-a-green-screen-41712-large.mp4',
    description: 'Walkthrough showcasing the interactive app UI elements, pink box callouts, and clean typographic lists.',
    skillsUsed: ['Screencast Cut', 'UI Animation', 'Micro-Transitions'],
    aspectRatio: '9:16'
  },
  {
    id: 'v11',
    title: 'Batayiye Series Interview',
    category: 'vertical',
    tag: 'Showcase',
    subtitle: 'Batayiye.',
    caption: 'Batayiye.',
    thumbnail: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-breaking-in-the-ocean-1527-large.mp4',
    description: 'An engaging client interview in a striped suit. Edited with bold italic caption overlay and sound enhancers.',
    skillsUsed: ['Audio Mastery', 'Creative Typography', 'Lower Thirds'],
    aspectRatio: '9:16'
  },
  {
    id: 'v12',
    title: 'Clean Sky Blue Block',
    category: 'vertical',
    tag: 'Minimal Space',
    subtitle: 'Ethereal Blue',
    caption: 'Sky Blue Block',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-waves-breaking-in-the-ocean-1527-large.mp4',
    description: 'A minimal soft light sky blue visual block representing visual breathing space in the portfolio sequence.',
    skillsUsed: ['Visual Balancing', 'Light Grading', 'Soft Contrast'],
    aspectRatio: '9:16'
  },

  // --- 9 HORIZONTAL ITEMS (16:9) ---
  {
    id: 'h1',
    title: 'They Started With Nothing',
    category: 'horizontal',
    tag: 'Concert Docu',
    subtitle: 'They Started With Nothing',
    caption: 'They started with absolutely nothing.',
    thumbnail: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-rock-concert-crowd-raising-their-hands-43059-large.mp4',
    description: 'Live concert crowd with a gritty cinematic grade and deep sub bass sound design.',
    skillsUsed: ['Audio Mastering', 'Live Pacing', 'Film Grain'],
    aspectRatio: '16:9'
  },
  {
    id: 'h2',
    title: 'Deadpool Action Cut',
    category: 'horizontal',
    tag: 'Action Animation',
    subtitle: 'Deadpool holding guns',
    caption: 'Deadpool',
    thumbnail: 'https://images.unsplash.com/photo-1608889174637-3c44f6326f2a?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-colored-particles-floating-in-space-40618-large.mp4',
    description: 'A high-impact animated sequence featuring Deadpool on a bright sky-blue canvas. Speed-ramped for maximum comedic action.',
    skillsUsed: ['Action Cutting', 'Pop Color Correction', 'Speed Ramps'],
    aspectRatio: '16:9'
  },
  {
    id: 'h3',
    title: 'Cinematic Back Shot',
    category: 'horizontal',
    tag: 'Cinematic Mood',
    subtitle: 'Back Portrait',
    caption: 'Back Portrait',
    thumbnail: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-man-walking-alone-in-the-city-at-night-42352-large.mp4',
    description: 'Atmospheric shot of a man from behind facing a dark space. Focuses on cinematic depth and high-contrast shadows.',
    skillsUsed: ['Contrast Modeling', 'High-Contrast Shadows', 'Slow Build-Up'],
    aspectRatio: '16:9'
  },
  {
    id: 'h4',
    title: 'Sticky Notes & Red Laser',
    category: 'horizontal',
    tag: 'Creative Brief',
    subtitle: 'Notes & Lasers',
    caption: 'Brainstorm',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-soft-warm-light-leaks-41617-large.mp4',
    description: 'Creative editing montage featuring document outlines, sticky notes, and clean technical camera overlays.',
    skillsUsed: ['Montage Flow', 'Technical HUDs', 'Sound Design'],
    aspectRatio: '16:9'
  },
  {
    id: 'h5',
    title: 'how is he???? Search Explainer',
    category: 'horizontal',
    tag: 'Explainer Anim',
    subtitle: 'how is he????',
    caption: 'how is he????',
    thumbnail: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-soft-warm-light-leaks-41617-large.mp4',
    description: 'A custom Google-style search animation with custom yellow vector stick figures exploring comical themes.',
    skillsUsed: ['Vector Layouts', 'Explainer Animation', 'Voice Pacing'],
    aspectRatio: '16:9'
  },
  {
    id: 'h6',
    title: 'Unspeakable Experience Booklet',
    category: 'horizontal',
    tag: 'Historical',
    subtitle: 'Unspeakable Experience',
    caption: 'Unspeakable Experience',
    thumbnail: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-colored-particles-floating-in-space-40618-large.mp4',
    description: 'Vintage documents and letters styled with historical stamps and visual overlays.',
    skillsUsed: ['Vintage Look', 'Asset Compiling', 'Aesthetic Overlays'],
    aspectRatio: '16:9'
  },
  {
    id: 'h7',
    title: 'Smile Emoji Split Scene',
    category: 'horizontal',
    tag: 'Storyboarding',
    subtitle: 'Split Creative Canvas',
    caption: 'Split Screen',
    thumbnail: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-animation-of-a-futuristic-city-with-flying-cars-45037-large.mp4',
    description: 'Split screen showcasing hand-drawn smiley face alongside illustrative character sketches on a textured background.',
    skillsUsed: ['Split Screen', 'Illustration Pairing', 'Cartoon Grids'],
    aspectRatio: '16:9'
  },
  {
    id: 'h8',
    title: 'Battle of Chaeronea Map',
    category: 'horizontal',
    tag: 'Map Explainer',
    subtitle: 'Battle of Chaeronea ⚔️',
    caption: 'Battle of Chaeronea',
    thumbnail: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-colored-particles-floating-in-space-40618-large.mp4',
    description: 'A historical map presentation detailing King Philip II\'s visual battle layouts and movements with comic stickers.',
    skillsUsed: ['Map Animating', 'Historical Visuals', 'Comic Overlays'],
    aspectRatio: '16:9'
  },
  {
    id: 'h9',
    title: 'Circle Badges & Avatars',
    category: 'horizontal',
    tag: 'Visual Assets',
    subtitle: 'Avatar Layout',
    caption: 'Social Circle',
    thumbnail: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
    videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-soft-warm-light-leaks-41617-large.mp4',
    description: 'Visual grid displaying stylized circle avatar banners like GAST666, LIKE-BOT, and more.',
    skillsUsed: ['Grid Presentation', 'Asset Display', 'Visual Pacing'],
    aspectRatio: '16:9'
  }
];
